version: '3.7'
services:
  moodle:
    image: moodlehq/moodle-php-apache:7.3
    volumes:
      - ${MOODLE_DIR}:/var/www/html
    ports:
      - "${MOODLE_PORT}:80"
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"